### PR TITLE
docs: use crontab instead of nano

### PR DESCRIPTION
**Pull request by ahjohannessen**

### CODE REVIEW

**Comment by cythoning** [comment]
Is using `crontab -e` much better practice? I thought I'd use `/etc/crontab` to be sure that pyznap runs as root.

**Comment by ahjohannessen** [comment]
I believe it is better practice to use `crontab`. Perhaps `sudo crontab -u user -e` ?

**Comment by ahjohannessen** [comment]
I updated the PR using `sudo crontab -u root -e` in order to be as explicit as possible. Now there is no doubt about who owns the cron table file.

**Comment by cythoning** [comment]
https://unix.stackexchange.com/questions/119481/how-come-crontab-e-is-different-from-less-etc-crontab

I think for system jobs it's better to use `/etc/crontab` or a file in `/etc/cron.d`. I'll leave it as it is, but thanks for pointing this out.

**Comment by ahjohannessen** [comment]
Yeah, no biggie.

**Pull request closed without merging**
